# Tarea 1 - Computacion Avanzada

In [1]:
# Librerias
import numpy as np

## Funciones

In [2]:
# Se definen los vectores

def vectors(n):
  # Se crean los vectores para el caso par
  if n%2==0:
    m=int(n/2-1)

    v=[]
    l=np.random.randint(-5,5,m)
    k=np.random.randint(-5,5,m)
    
    l_0=l[0]
    ks=np.append(l_0, [k])
    
    v=np.concatenate((ks, -ks))
    
    v_0=[0,0]
    v_=np.concatenate((v_0, l, -l))

    return v, v_
  
  # Se crean los vectores para el caso par
  else:
    m=int((n-3)/2)

    l=np.random.randint(-5,5,m)
    k=np.random.randint(-5,5,m+1)
    
    l_0=np.array([0])
    ks=np.append(l_0, [k])
    u=np.concatenate((ks, -k))

    k_0=k[0]
    ls=np.append(l, [k_0])
    ls=np.append(ls, [0])
    ls2=np.append(l, [k_0])
    u_=np.concatenate((ls, -ls2))

    return u, u_

In [3]:
def set_solutions(x, y):
    x=np.array(x)
    y=np.array(y)
    
    z=sum(x*(y**2))*x-sum((x**2)*y)*y
    
    div = np.gcd.reduce(z)
    if div!=0:
        solution=z/div
        return solution, div
    else:
        solution=z
        return solution, 1

In [4]:
# Verificación quirales o vectorlike

def vector_like_comprobation(v):
    
    uniq_abs = np.unique(np.abs(v)).shape[0]
    uniq_all = np.unique(v).shape[0]
    
    if uniq_abs == uniq_all:
        #quiral solution
        return (1)
    else:
        #vector-like solution
        return (0)

## Verificación de las funciones

In [5]:
k=[1,-2]
l=[1,2]
vp=[l[0],k[0],k[1],-l[0],-k[0],-k[1]]
vm=[0,0,l[0],l[1],-l[0],-l[1]]
k=np.array(k)
l=np.array(l)
vp=np.array(vp)
vm=np.array(vm)

In [6]:
z, gcd=set_solutions(vp,vm)
z, gcd

(array([ 1.,  1.,  1.,  5., -4., -4.]), 1)

## Aplicación de las funciones

In [7]:
n=6
x, y= vectors(n)
x,y

(array([-1, -2,  2,  1,  2, -2]), array([ 0,  0, -1, -1,  1,  1]))

In [8]:
solutions, gcd=set_solutions(x, y)
solutions, gcd

(array([-1., -2.,  3.,  2.,  1., -3.]), 3)

## Comprobacion para n par

In [9]:
# Iteramos las solucines en busca de los que cumplan la condicion de suma y suma al cuadrado 
n=6
for i in range(0,100):
    x, y= vectors(n)
    x=np.array(x)
    y=np.array(y)
    solution, gcd=set_solutions(x, y)
    # Se aplican las condiciones de la suma y la suma al cubo
    if np.sum(solution)==0 and np.sum(solution**3)==0:
        # Se descartan soluciones vector like
        if vector_like_comprobation(solution)==1:
            p=0
            for i in solution:
                # Se dejan las soliciones que cumpla con que sus entradasean menor a 30
                if i<=30:
                    p+=1
            # Se descartan las soluciones triviales
            if p==len(solution) and np.all(solution==0)==False:
                #Se imprime la solucion
                print(solution, gcd)

[ 1.  0. -8.  5.  9. -7.] 9
[-11. -11.  16.   8.  17. -19.] 4
[-30. -24.  29.  26.  19. -20.] 36
[-28.  -7.  20.  25.   1. -11.] 8
[-7.  0. -9. 10.  2.  4.] 8
[ -2.  10.   3. -13. -13.  15.] 10
[ 10. -15.  22. -21.  -7.  11.] 2
[-14. -14.  -1.  17.   8.   4.] 16
[-15.   5. -11.   8.  16.  -3.] 2
[-14. -14.  11.   5.  -4.  16.] 1
[-15.   5. -21.   7.   1.  23.] 12
[-11. -11. -19.  17.   8.  16.] 1
[ 2.  0. -9. -7. 10.  4.] 16
[ -3.  -1. -15.  11.  13.  -5.] 6
[ 24.  -6.   4. -29.  26. -19.] 12
[  5.   0. -26.  28.  11. -18.] 3


## Comprobacion para n impar

In [10]:
# Iteramos las solucines en busca de los que cumplan la condicion de suma y suma al cuadrado 
n=7
for i in range(0,100):
    x, y= vectors(n)
    x=np.array(x)
    y=np.array(y)
    solution, gcd=set_solutions(x, y)
    # Se aplican las condiciones de la suma y la suma al cubo
    if np.sum(solution)==0 and np.sum(solution**3)==0:
        # Se descartan soluciones vector like
        if vector_like_comprobation(solution)==1:
            p=0
            for i in solution:
                # Se dejan las soliciones que cumpla con que sus entradasean menor a 30
                if i<=30:
                    p+=1
            # Se descartan las soluciones triviales
            if p==len(solution) and np.all(solution==0)==False:
                #Se imprime la solucion
                print(solution, gcd)

[ 18. -21.  20. -14.   3.   7. -13.] 3
[ 3.  7. -6. -1. -6. -1.  4.] 51
[  4. -18.  -7. -20.   6.  23.  12.] 2
[ 25. -27.  -5.  14. -18.  20.  -9.] 1
[ 13.  25. -28.  -1. -12. -24.  27.] 4
[  6. -14.  11.  21.   8. -14. -18.] 4
