# Tarea 1 - Computacion Avanzada

In [1]:
# Librerias
import numpy as np
import multiprocessing

## Funciones

In [2]:
# Se definen los vectores

def vectors(n):
  # Se crean los vectores para el caso par
  if n%2==0:
    m=int(n/2-1)

    v=[]
    l=np.random.randint(-5,5,m)
    k=np.random.randint(-5,5,m)
    
    l_0=l[0]
    ks=np.append(l_0, [k])
    
    v=np.concatenate((ks, -ks))
    
    v_0=[0,0]
    v_=np.concatenate((v_0, l, -l))

    return v, v_
  
  # Se crean los vectores para el caso par
  else:
    m=int((n-3)/2)

    l=np.random.randint(-5,5,m)
    k=np.random.randint(-5,5,m+1)
    
    l_0=np.array([0])
    ks=np.append(l_0, [k])
    u=np.concatenate((ks, -k))

    k_0=k[0]
    ls=np.append(l, [k_0])
    ls=np.append(ls, [0])
    ls2=np.append(l, [k_0])
    u_=np.concatenate((ls, -ls2))

    return u, u_

In [3]:
def set_solutions(x, y):
    x=np.array(x)
    y=np.array(y)
    
    z=sum(x*(y**2))*x-sum((x**2)*y)*y
    
    div = np.gcd.reduce(z)
    if div!=0:
        solution=z/div
        return solution, div
    else:
        solution=z
        return solution, 1

In [4]:
# Verificación quirales o vectorlike

def vector_like_comprobation(v):
    
    uniq_abs = np.unique(np.abs(v)).shape[0]
    uniq_all = np.unique(v).shape[0]
    
    if uniq_abs == uniq_all:
        #quiral solution
        return (1)
    else:
        #vector-like solution
        return (0)

## Verificación de las funciones

In [5]:
k=[1,-2]
l=[1,2]
vp=[l[0],k[0],k[1],-l[0],-k[0],-k[1]]
vm=[0,0,l[0],l[1],-l[0],-l[1]]
k=np.array(k)
l=np.array(l)
vp=np.array(vp)
vm=np.array(vm)

In [6]:
z, gcd=set_solutions(vp,vm)
z, gcd

(array([ 1.,  1.,  1.,  5., -4., -4.]), 1)

## Aplicación de las funciones

In [7]:
n=6
x, y= vectors(n)
x,y

(array([ 3, -2,  1, -3,  2, -1]), array([ 0,  0,  3,  3, -3, -3]))

In [8]:
solutions, gcd=set_solutions(x, y)
solutions, gcd

(array([-3.,  2., -6., -2.,  3.,  6.]), 9)

## Comprobacion para n par

In [9]:
# Iteramos las solucines en busca de los que cumplan la condicion de suma y suma al cuadrado 
n=6
for i in range(0,100):
    x, y= vectors(n)
    x=np.array(x)
    y=np.array(y)
    solution, gcd=set_solutions(x, y)
    # Se aplican las condiciones de la suma y la suma al cubo
    if np.sum(solution)==0 and np.sum(solution**3)==0:
        # Se descartan soluciones vector like
        if vector_like_comprobation(solution)==1:
            p=0
            for i in solution:
                # Se dejan las soliciones que cumpla con que sus entradasean menor a 30
                if i<=30:
                    p+=1
            # Se descartan las soluciones triviales
            if p==len(solution) and np.all(solution==0)==False:
                #Se imprime la solucion
                print(solution, gcd)

[ -5.  10.  -4.   2. -11.   8.] 3
[ -5. -25.  -8.  -1.  23.  16.] 6
[ -6.  24. -29.  26. -19.   4.] 12
[  7. -14. -16.  18.   9.  -4.] 7
[ 1. -2.  5. -6. -3.  5.] 16
[  1.  -3. -25.  19.  23. -15.] 2
[ -4.  -4. -31.  25.  25. -11.] 8
[-11. -22.   1.  14.  21.  -3.] 1
[ -8. -12.  -6.   5.  10.  11.] 10
[ 2. -5.  3. -1.  6. -5.] 12
[-14.  -7. -26.  17.   5.  25.] 6
[-5. -5. -1.  3.  6.  2.] 16
[  5. -10. -11.  13.   1.   2.] 2
[  7. -14. -10.  15.   3.  -1.] 1


## Comprobacion para n impar

In [10]:
# Iteramos las solucines en busca de los que cumplan la condicion de suma y suma al cuadrado 
n=7
for i in range(0,100):
    x, y= vectors(n)
    x=np.array(x)
    y=np.array(y)
    solution, gcd=set_solutions(x, y)
    # Se aplican las condiciones de la suma y la suma al cubo
    if np.sum(solution)==0 and np.sum(solution**3)==0:
        # Se descartan soluciones vector like
        if vector_like_comprobation(solution)==1:
            p=0
            for i in solution:
                # Se dejan las soliciones que cumpla con que sus entradasean menor a 30
                if i<=30:
                    p+=1
            # Se descartan las soluciones triviales
            if p==len(solution) and np.all(solution==0)==False:
                #Se imprime la solucion
                print(solution, gcd)

[-1. -6.  3.  4.  7. -6. -1.] 6
[  0.  11.  16. -21. -21.  24.  -9.] 2
[ 14.  17.  -5. -20. -10.  -9.  13.] 6
[ 12. -20.  21. -15.   8.  -5.  -1.] 20
[  7. -13.   7.   2.  -8.  14.  -9.] 16
[ 5. -6. -3. -2. -9.  8.  7.] 8
[ -3. -22.   0.  -4.  19.  -6.  16.] 10
[ 24.  13. -21.   5. -19.  -3.   1.] 6
[ 20. -19. -12.   9.   7.  -8.   3.] 6
[  4. -13.  -3. -12.   8.   1.  15.] 18


## Paralelización

In [ ]:
# Paralelizacion

valores = np.full(10, 5)


pool = multiprocessing.Pool(2)
result = pool.map(set_solutions, valores)

for z in np.unique(result, axis=0):
    print(z)